### ISSUE TITLE
unable to login running locally

### ISSUE THREAD

**Issue by stuartcrobinson** [marioperezhurtado/DatsCap#2]
i've tried setting up google and github auth, tried using email several times.  looks like it pointed to the wrong port (3000, which wasn't being used locally). i tried changing that. still nothing is working

**Comment by marioperezhurtado** [comment]
Can you provide more info? What exactly is the problem? Thanks.

**Comment by stuartcrobinson** [comment]
it sends me the confirmation link, and i click it, but it doesn't point to the right port number.  and when i change the port, it still doesn't work.  it just redirects me to the signin page but that email/pw still doesn't work

**Comment by stuartcrobinson** [comment]
ok update:

it looks like all my users were successfully created and verified.  i turned off email verification for the supabase project, and it's still not letting me log in.  just redirects back to signin page when i try.  console errors w/ context:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/12928716/213898332-93da517c-b642-4ac8-87e8-7d8864a5d813.png">

**Comment by marioperezhurtado** [comment]
I think the problem is that when you create a new user, you are not creating the new entry in the "profiles" table.

So it fails when trying to fetch your profile data and does not log in.

I now remembered I ran this quick start query at the very beginning of my project, I should have included it here.

![Screenshot from 2023-01-22 12-08-21](https://user-images.githubusercontent.com/111692675/213912894-f83536b5-311a-4876-97fc-6252079ff656.png)

That query sets up the "profiles" table, the rls policies, and a trigger that inserts the new profile every time a user gets created.

It also creates an "avatars" storage bucket, but you can just delete it if you are not using it.


Let me know if that works for you. I will include it in the readme. Thanks :)
